NUM_WORKER_NODES=2
IP_NW="192.168.31."
IP_START=200

Vagrant.configure("2") do |config|
  # Update and install net-tools
  config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt install net-tools -y
  SHELL

  # Install Docker
  $script = <<-SCRIPT
    curl https://releases.rancher.com/install-docker/20.10.sh | sh
    sudo usermod -aG docker ${USER}
    echo "export PATH=/usr/bin:\$PATH" >>  ~/.bashrc
  SCRIPT
  config.vm.provision "shell", inline: $script, privileged: false

  # Configure wich box (image) will use the VMs (ubuntu-20.04 base box)
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_check_update = true


  config.vm.define "rancher" do |rancher|
    rancher.vm.hostname = "rancher"

    # Add a Public Network
    rancher.vm.network "public_network", :adapter=>2, ip: IP_NW + "#{IP_START}", bridge: "wlp0s20f3",  use_dhcp_assigned_default_route: false
    # Add Default Router to public Network
    rancher.vm.provision "shell", run: "always", inline: "sudo route add default gw 192.168.31.1"
    # Delete Router of the eth0 interface
    rancher.vm.provision "shell", run: "always", inline: "sudo route del default gw 10.0.2.2 eth0"

    # Configure vm resources
    rancher.vm.provider "virtualbox" do |vb|
        vb.memory = 3584
        vb.cpus = 4
    end
  end

  
  config.vm.define "master" do |master|
    master.vm.hostname = "master-node"

    # Add a Public Network
    master.vm.network "public_network", :adapter=>2, ip: IP_NW + "#{IP_START+1}", bridge: "wlp0s20f3",  use_dhcp_assigned_default_route: false
    # Add Default Router to public Network
    master.vm.provision "shell", run: "always", inline: "sudo route add default gw 192.168.31.1"
    # Delete Router of the eth0 interface
    master.vm.provision "shell", run: "always", inline: "sudo route del default gw 10.0.2.2 eth0"

    # Configure vm resources
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 3
    end
  end


  (1..NUM_WORKER_NODES).each do |i|
    config.vm.define "node0#{i}" do |node|
      node.vm.hostname = "worker-node0#{i}"

      # Add a Public Network
      node.vm.network "public_network", :adapter=>2, ip: IP_NW + "#{IP_START + 1 + i}", bridge: "wlp0s20f3",  use_dhcp_assigned_default_route: false
      # Add Default Router to public Network
      node.vm.provision "shell", run: "always", inline: "sudo route add default gw 192.168.31.1"
      # Delete Router of the eth0 interface
      node.vm.provision "shell", run: "always", inline: "sudo route del default gw 10.0.2.2 eth0"
      
      # Configure vm resources
      node.vm.provider "virtualbox" do |vb|
          vb.memory = 2560
          vb.cpus = 4
      end
    end
  end
end
